// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function() {
    var AlgebraError;
    AlgebraError = (function(_super) {
      __extends(AlgebraError, _super);

      function AlgebraError(expr, variable, postscript) {
        if (postscript == null) {
          postscript = null;
        }
        AlgebraError.__super__.constructor.call(this, "Unsolvable: " + expr + " for " + variable + (postscript ? "; " + postscript : ""));
      }

      return AlgebraError;

    })(Error);
    return AlgebraError;
  });

}).call(this);
