// Generated by CoffeeScript 1.6.3
/* Coffeequate - http://github.com/MatthewJA/Coffeequate*/


(function() {
  require.config({
    baseUrl: "./"
  });

  define(["operators", "Expression", "parse"], function(operators, Expression, parse) {
    var CQ;
    CQ = function(input) {
      var left, right, val, _ref;
      if (/\=/.test(input)) {
        _ref = input.split("="), left = _ref[0], right = _ref[1];
        val = new operators.Add(parse.stringToExpression(right), new operators.Mul(parse.stringToExpression(left), "-1"));
        return new Expression(val);
      } else {
        return new Expression(input);
      }
    };
    return CQ;
  });

}).call(this);
