// Generated by CoffeeScript 1.6.3
(function() {
  var constants;

  constants = {
    c: 299792458,
    G: 6.67384e-11,
    π: Math.PI,
    PI: Math.PI,
    E: Math.E,
    e: Math.E,
    ε0: 8.85418782e-12,
    μ0: 1.25663706e-6,
    k: 1.3806488e-23,
    h: 6.62606957e-34,
    hbar: 1.05457173e-34,
    NA: 6.02214129e23,
    mu: 1.66053892e-27,
    a0: 5.29e-11,
    ke: 1 / (4 * Math.PI * 8.85418782e-12),
    ec: 1.60217657e-19,
    R: 8.3144621
  };

  define(function() {
    return constants;
  });

}).call(this);
