// Generated by CoffeeScript 1.6.3
(function() {
  define(["operators/Add", "operators/Mul", "operators/Pow"], function(Add, Mul, Pow) {
    return {
      Add: Add,
      Mul: Mul,
      Pow: Pow
    };
  });

}).call(this);
