// Generated by CoffeeScript 1.6.3
(function() {
  define(["nodes", "terminals", "operators", "require"], function(nodes, terminals, operators, require) {
    return nodes.BasicNode.prototype.getUncertainty = function() {
      var Add, Constant, Mul, Pow, Uncertainty, out, stuff, variable, variables, _i, _len;
      Mul = operators.Mul;
      Pow = operators.Pow;
      Add = operators.Add;
      Uncertainty = terminals.Uncertainty;
      Constant = terminals.Constant;
      variables = this.getAllVariables();
      out = [];
      for (_i = 0, _len = variables.length; _i < _len; _i++) {
        variable = variables[_i];
        stuff = new Mul(new terminals.Uncertainty(variable), this.differentiate(variable));
        out.push(new Pow(stuff, 2));
      }
      return new Pow((function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args);
        return Object(result) === result ? result : child;
      })(Add, out, function(){}), new terminals.Constant(1, 2)).expandAndSimplify();
    };
  });

}).call(this);
